### ISSUE TITLE
Custom colon

### ISSUE THREAD

**Issue by bantuist** [antonfisher/react-simple-timefield#1]
Hi @antonfisher, how would you (or would you) recommend customizing the hour/minute separator colon? I'm making a timer and I wanted to toggle the hour/minute colon as a second indicator.

**Comment by antonfisher** [comment]
Hi @bantuist, thank you for your feedback!
I just pushed custom colon property, called it "colon".
Please check it out, if you have any feedback on it.

**Comment by bantuist** [comment]
Nice! Looks good. Did you get an Unknown prop `colon` on <input> tag warning in your example?

**Comment by antonfisher** [comment]
Yes, good catch, I've pushed the fix. Thank you!
