### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by NicholasLYang** [antonfisher/react-simple-timefield#16]
Hi, I'm using your package in a TypeScript app, but I noticed that the package doesn't have any declarations.

I'm open to making a declaration file, but one thought I figured I might float by you is to just convert the code to TypeScript. The package is mostly one file that I can probably convert without too much trouble. That way the declarations will stay up to date even with code changes.

If you have some particular reason or preference for not using TypeScript, then that's perfectly fine too :D

Thanks,
Nicholas

**Comment by antonfisher** [comment]
Hi Nicholas!
That's actually a good idea to convert the whole thing to TypeScript. I have no experience with TypeScript so far, mostly worked with Flow. I'd appreciate if you could do a PR. Also, I'm not sure, we probably need to replace the build process in this case (do we need babel?)
Thank you!

**Comment by NicholasLYang** [comment]
Sure! I'll get on it in a few days. The build process shouldn't be too different, we'll just use TypeScript's compiler instead of Babel.

**Comment by NicholasLYang** [comment]
Opened up a PR. I need some help on the ESLint config. I'm trying to use `overrides` to lint tsx files but I'm not sure if it's working. I don't get any errors, which I suspect means it's not working.
