### ISSUE TITLE
Dist contains ES6 modules

### ISSUE THREAD

**Issue by csvan** [antonfisher/react-simple-timefield#26]
As of the latest release, line 36 in the `dist/index.js` file now contains:

```
import React from 'react';
```

This breaks a lot of projects using for example Jest, where items in node_modules are by default not passed through Babel.

People using Jest can add the following to their configs as a temporary workaround, but it's not optimal:

```
transformIgnorePatterns: ['node_modules/(?!react-simple-timefield)']
```

**Comment by antonfisher** [comment]
Good catch! Just pushed https://www.npmjs.com/package/react-simple-timefield/v/3.2.3 :+1:
