### ISSUE TITLE
User is able to type invalid time

### ISSUE THREAD

**Issue by rygiewicz** [antonfisher/react-simple-timefield#3]
Hello.

Thank you for creating this and sharing it with others. I found a small bug I would like to report.
If you select part of the input text and type any character, it will allow it.

Best regards,
Paweł

**Comment by antonfisher** [comment]
Hi, thank you for the issue! This is an interesting one, I'll check what can I do here.

**Comment by antonfisher** [comment]
Should be fixed with [2.0.3](https://github.com/antonfisher/react-simple-timefield/releases/tag/v2.0.3)
