### ISSUE TITLE
How to allow 24:00

### ISSUE THREAD

**Issue by ImanMh** [antonfisher/react-simple-timefield#7]
Is it possible to allow user to type 24:00 inside input component?

**Comment by antonfisher** [comment]
Hi, this seems to be not a valid time, but you can change fix it locally. Copy file `https://github.com/antonfisher/react-simple-timefield/blob/master/src/index.js` and change this:
- https://github.com/antonfisher/react-simple-timefield/blob/master/src/index.js#L28 "3" to "4"
- https://github.com/antonfisher/react-simple-timefield/blob/master/src/index.js#L31 "3" to "4"
and it should work fine.

**Comment by ImanMh** [comment]
Thanks, I guess it's not possible without modifying the component code. But thanks for your guide.
