### ISSUE TITLE
User can type letter when Component first loads

### ISSUE THREAD

**Issue by technoplato** [antonfisher/react-simple-timefield#9]
Repro:

1) Load component
2) Type 'a' as the first character before any others
3) Observe a is entered into input

**Comment by technoplato** [comment]
I think one may have to 'tab' into the field for this to occur

**Comment by technoplato** [comment]
Highlighting the entire field will yield this bug as well.

**Comment by ManojKumarNagaraj** [comment]
HI,
Can i know what can be the exact fix for this because i have started using this plugin in the forms.

**Comment by technoplato** [comment]
In your listener for changes to the text, check for non numbers and prevent them from changing your state.

**Comment by antonfisher** [comment]
Working on it...

**Comment by antonfisher** [comment]
I published version [2.0.2](https://www.npmjs.com/package/react-simple-timefield/v/2.0.2), should be OK now.
